/** GENERATED — where Framer's runtime gets this site's text from now.
 *
 *  Framer's compiled chunks and CMS data carry their own copy of every string
 *  the runtime renders. Without this file, an edit to a copy.ts changes the
 *  HTML the server sends and nothing else: the runtime re-renders its own
 *  copy a moment later. src/render.ts reads this table on every render and
 *  regenerates those files from your source, so what the runtime renders is
 *  what you wrote. Regenerated by the converter; nothing to edit here. */
import { copy as copy0 } from "@/src/sections/home/Navbar";
import { copy as copy1 } from "@/src/views/HomePage";
import { copy as copy2 } from "@/src/views/Section404Page";

export interface RuntimeText {
  /** Its key in public/assets/framer/fnj-content.mjs, when a chunk renders it. */
  key?: string;
  /** The CMS data files that carry it, when a collection page renders it. */
  cms?: string[];
  /** The text as converted — what the shipped files contain. */
  original: string;
  /** The text now, read from your source. */
  get: () => string | undefined;
}

/** 11 string(s) the runtime renders. */
export const runtimeText: RuntimeText[] = [
  { key: "features", original: "Features", get: () => copy0.features },
  { key: "how_it_works", original: "How it works", get: () => copy0.howItWorks },
  { key: "tariffs", original: "Tariffs", get: () => copy0.tariffs },
  { key: "testimonials", original: "Testimonials", get: () => copy0.testimonials },
  { key: "faq", original: "FAQ", get: () => copy0.faq },
  { key: "log_in", original: "Log in", get: () => copy0.logIn },
  { key: "get_started", original: "Get started", get: () => copy0.getStarted },
  { key: "buy_navbar", original: "Buy Navbar", get: () => copy1.buyNavbar },
  { key: "buy_from_5", original: "Buy From $5", get: () => copy1.buyFrom5 },
  { key: "page_not_found", original: "Page Not Found", get: () => copy2.pageNotFound },
  { key: "back_to_home", original: "Back to Home", get: () => copy2.backToHome },
];

/** A collection record, as src/render.ts reads it: any field by name. */
export type CollectionRecord = { route: string } & Record<string, string | undefined>;

/** Every collection by name, for the member pages' hydration payloads. */
export const collections: Record<string, CollectionRecord[]> = {

};
