/** GENERATED — where Framer's runtime gets this site's text from now.
 *
 *  Framer's compiled chunks and CMS data carry their own copy of every string
 *  the runtime renders. Without this file, an edit to a copy.ts changes the
 *  HTML the server sends and nothing else: the runtime re-renders its own
 *  copy a moment later. src/render.ts reads this table on every render and
 *  regenerates those files from your source, so what the runtime renders is
 *  what you wrote. Regenerated by the converter; nothing to edit here. */
import { copy as copy0 } from "@/src/sections/home/Container/copy";
import { copy as copy1 } from "@/src/sections/style-2/Container/copy";
import { copy as copy2 } from "@/src/sections/style-3/Container/copy";
import { copy as copy3 } from "@/src/views/Section404Page";

export interface RuntimeText {
  /** Its key in public/assets/framer/fnj-content.mjs, when a chunk renders it. */
  key?: string;
  /** The CMS data files that carry it, when a collection page renders it. */
  cms?: string[];
  /** The text as converted — what the shipped files contain. */
  original: string;
  /** The text now, read from your source. */
  get: () => string | undefined;
}

/** 17 string(s) the runtime renders. */
export const runtimeText: RuntimeText[] = [
  { key: "this_background_effect_won_t_work_on_mob", original: "This background effect won't work on mobile since it needs to track the cursor.", get: () => copy0.thisBackgroundEffectWon },
  { key: "displacement_grid", original: "Displacement Grid", get: () => copy0.displacementGrid },
  { key: "example_1", original: "Example 1", get: () => copy0.example1 },
  { key: "example_2", original: "Example 2", get: () => copy0.example2 },
  { key: "example_3", original: "Example 3", get: () => copy0.example3 },
  { key: "this_background_effect_won_t_work_on_mob", original: "This background effect won't work on mobile since it needs to track the cursor.", get: () => copy1.thisBackgroundEffectWon },
  { key: "displacement_grid", original: "Displacement Grid", get: () => copy1.displacementGrid },
  { key: "example_1", original: "Example 1", get: () => copy1.example1 },
  { key: "example_2", original: "Example 2", get: () => copy1.example2 },
  { key: "example_3", original: "Example 3", get: () => copy1.example3 },
  { key: "this_background_effect_won_t_work_on_mob", original: "This background effect won't work on mobile since it needs to track the cursor.", get: () => copy2.thisBackgroundEffectWon },
  { key: "displacement_grid", original: "Displacement Grid", get: () => copy2.displacementGrid },
  { key: "example_1", original: "Example 1", get: () => copy2.example1 },
  { key: "example_2", original: "Example 2", get: () => copy2.example2 },
  { key: "example_3", original: "Example 3", get: () => copy2.example3 },
  { key: "page_not_found", original: "Page Not Found", get: () => copy3.pageNotFound },
  { key: "back_to_home", original: "Back to Home", get: () => copy3.backToHome },
];

/** A collection record, as src/render.ts reads it: any field by name. */
export type CollectionRecord = { route: string } & Record<string, string | undefined>;

/** Every collection by name, for the member pages' hydration payloads. */
export const collections: Record<string, CollectionRecord[]> = {

};
