/** GENERATED — where Framer's runtime gets this site's text from now.
 *
 *  Framer's compiled chunks and CMS data carry their own copy of every string
 *  the runtime renders. Without this file, an edit to a copy.ts changes the
 *  HTML the server sends and nothing else: the runtime re-renders its own
 *  copy a moment later. src/render.ts reads this table on every render and
 *  regenerates those files from your source, so what the runtime renders is
 *  what you wrote. Regenerated by the converter; nothing to edit here. */
import { copy as copy0 } from "@/src/sections/home/Variant1";
import { copy as copy1 } from "@/src/views/HomePage";
import { copy as copy2 } from "@/src/views/Section404Page";

export interface RuntimeText {
  /** Its key in public/assets/framer/fnj-content.mjs, when a chunk renders it. */
  key?: string;
  /** The CMS data files that carry it, when a collection page renders it. */
  cms?: string[];
  /** The text as converted — what the shipped files contain. */
  original: string;
  /** The text now, read from your source. */
  get: () => string | undefined;
}

/** 15 string(s) the runtime renders. */
export const runtimeText: RuntimeText[] = [
  { key: "tyron", original: "TYRON", get: () => copy0.tyron },
  { key: "design", original: "design", get: () => copy0.design },
  { key: "work", original: "work", get: () => copy0.work },
  { key: "process", original: "process", get: () => copy0.process },
  { key: "your_files", original: "Your files", get: () => copy0.yourFiles2 },
  { key: "wallet", original: "Wallet", get: () => copy0.wallet2 },
  { key: "cover_album", original: "Cover album", get: () => copy0.coverAlbum },
  { key: "organize_your_content_with", original: "Organize your content with", get: () => copy0.organizeYourContentWith },
  { key: "a_delightful_folder_interaction", original: "a delightful folder interaction.", get: () => copy0.aDelightfulFolderInteraction },
  { key: "present_financial_information_with_a_pre", original: "Present financial information with a premium hover experience.", get: () => copy0.presentFinancialInformationWith },
  { key: "transform_static_album_art_into_an_engag", original: "Transform static album art into an engaging music interaction.", get: () => copy0.transformStaticAlbumArt },
  { key: "hover_components", original: "Hover components", get: () => copy1.hoverComponents },
  { key: "by_zakyyy_dsgn", original: "by zakyyy.dsgn", get: () => copy1.byZakyyyDsgn },
  { key: "page_not_found", original: "Page Not Found", get: () => copy2.pageNotFound },
  { key: "back_to_home", original: "Back to Home", get: () => copy2.backToHome },
];

/** A collection record, as src/render.ts reads it: any field by name. */
export type CollectionRecord = { route: string } & Record<string, string | undefined>;

/** Every collection by name, for the member pages' hydration payloads. */
export const collections: Record<string, CollectionRecord[]> = {

};
